# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Prime Dictation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prime Dictation
use_frameworks!
pod 'ProgressHUD'
pod 'MSGraphMSALAuthProvider'
pod 'MSGraphClientSDK'

end
