# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Prime Dictation' do


  # Pods for Prime Dictation
use_frameworks!
pod 'ProgressHUD'
pod 'MSGraphClientSDK'
pod 'MSAL'

end
